language: node_js
node_js:
  - v12.18.3 
notifications: 
  email: false
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database initiateco;' -U postgres
  - psql -c "CREATE USER user1 WITH PASSWORD 'asdf';" -U postgres
  - npm run setup
  