language: node_js
node_js:
  - v12.18.3 
notifications: 
  email: false
services:
  - postgresql
before_script:
  - npm install
  - npm run setup
  - psql -c 'create database initiateco;' -U postgres
  